---
title: "Formation-R-perfectionnement"
subtitle: "Module Création de graphiques avec ggplot2"
date: today
date-format: "DD/MM/YYYY"
author: "SSP/DEMESIS"
description: |
  Support de formation R-perfectionnement : Module Création de graphiques avec ggplot2 au SSM Agriculture
slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide
fig-cap-location: bottom
# toc: true
# toc-title: Sommaire
# toc-depth: 1
# toc-float: true
#multiplex: true
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
  markdown: 
    wrap: 72
---

# Avant-propos{.unnumbered}

## Sommaire

|                                              |                              |
|----------------------------------------------|------------------------------|
| 1 - Le package ggplot2                       | 8 - Les courbes              |
| 2 - Initialisation d'un graphique            | 9 - Les camemberts           |
| 3 - Les différentes géométries de graphiques | 10 - Les boîtes à moustaches |
| 4 - Croisement avec une autre variable       | 11 - Ajout de libellés       |
| 5 - Les diagrammes en barres                 | 12 - Habillage du graphique  |
| 6 - Les histogrammes                         | 13 - Sauvegarde du graphique |
| 7 - Les nuages de points                     | 14 - Liens                   |


## Avant-propos

Ce diaporama de formation a été rédigé dans le but d'être le support visuel des formations dispensées au [SSM Agriculture](https://agreste.agriculture.gouv.fr/).

Ces formations _de perfectionnement_ s'adressent aux agents qui ont suivi **la formation R
initialisation** (ou le **module de rappels sur la formation initiation**) ainsi que le **module sur les fonctions**, voir sur le [site des formations dispensées au MASA](https://ssm-agriculture.github.io/site-formations-R/).

## Avant-propos

Les différents modules sont donnés en présentiel sur une durée **d'une journée** (avant la formation _R-perfectionnement_ était groupée sur 3 jours).

::: callout-note
## Champ couvert par cette formation

**Ce support couvre le module Création de graphiques avec ggplot2 dans l'environnement R du Ministère.**

Pour information, Les Modules de la formation R-perfectionnement sont :

-   01 - Module Rappels
-   02 - Module Fonctions
-   03 - Module Cartes statiques et interactives
-   04 - Module Création de graphiques avec ggplot2
-   05 - Module Quarto
-   06 - Module Parquet
-   07 - Module Initiation à l'écriture d'applications Shiny

Les modules sont orientés pour être utiles aux agents du SSM Agriculture et se concentrent sur une utilisation de R via [RStudio](https://posit.co/download/rstudio-desktop/) qui est mise à
disposition des agents sur la plateforme interne Cerise basée sur RStudio Workbench.
:::

{{< include 01_ggplot2.qmd >}}

{{< include 02_init.qmd >}}

{{< include 03_geometrie.qmd >}}

{{< include 04_croisement.qmd >}}

{{< include 05_barres.qmd >}}

{{< include 06_histogrammes.qmd >}}

{{< include 07_nuages.qmd >}}

{{< include 08_courbes.qmd >}}

{{< include 09_camenberts.qmd >}}

{{< include 10_moustaches.qmd >}}

{{< include 11_libelles.qmd >}}

{{< include 12_habillage-graphique.qmd >}}

{{< include 13_sauvegarde.qmd >}}

{{< include 14_exercice.qmd >}}
